"""Rebuild the readings table so pgAdmin shows the requested column order.

PostgreSQL cannot move an existing column with ALTER TABLE. This migration
keeps the original table as a backup and creates a partitioned replacement.
"""

from datetime import datetime, timezone
from pathlib import Path
import re
import sys

import psycopg
from psycopg import sql


PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from config.settings import load_settings  # noqa: E402


FIRST_AFTER_TIMESTAMP_SOURCE = [
    "active_energy_received_out_of_load",
    "reactive_energy_received",
    "apparent_energy_received",
]

NON_NUMERIC_COLUMNS = {
    "id",
    "meter_id",
    "timestamp",
    "meter_timestamp",
    "collected_at",
    "reading_date",
    "reading_time",
    "timestamp_source",
    "meter_name",
    "accumulated_energy_reset_date_time",
    "present_date_and_time",
    "peak_demand_datetime",
}


def replacement_partition_name(old_partition: str) -> str:
    match = re.fullmatch(r"(?:readings|readings_reordered)_(\d{4}_\d{2}_\d{2})", old_partition)
    if match is None:
        raise ValueError(f"Unexpected readings partition name: {old_partition}")
    return f"readings_{match.group(1)}"


def main() -> None:
    settings = load_settings()
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    backup_name = f"readings_backup_{stamp}"
    replacement_name = "readings_reordered"

    with psycopg.connect(
        host=settings.db_host,
        port=settings.db_port,
        dbname=settings.db_name,
        user=settings.db_user,
        password=settings.db_password,
    ) as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT column_name, format_type(a.atttypid, a.atttypmod),
                       column_default, is_nullable
                FROM information_schema.columns c
                JOIN pg_attribute a ON a.attrelid = (c.table_schema || '.' || c.table_name)::regclass
                                   AND a.attname = c.column_name
                WHERE c.table_schema = current_schema()
                  AND c.table_name = 'readings'
                ORDER BY ordinal_position
                """
            )
            metadata = cursor.fetchall()
            if not metadata:
                raise RuntimeError("public.readings was not found")

            names = [row[0] for row in metadata]
            desired = ["id", "meter_id", "meter_name", "timestamp", "meter_timestamp",
                       "collected_at", "reading_date", "reading_time", "timestamp_source"]
            desired += [name for name in FIRST_AFTER_TIMESTAMP_SOURCE if name in names]
            desired += [name for name in names if name not in desired]
            by_name = {row[0]: row for row in metadata}
            numeric_columns = set(names) - NON_NUMERIC_COLUMNS

            cursor.execute(sql.SQL("DROP TABLE IF EXISTS {} CASCADE").format(sql.Identifier(replacement_name)))
            definitions = []
            for name in desired:
                _, type_sql, column_default, is_nullable = by_name[name]
                if name == "id":
                    definition = sql.SQL("{} BIGINT GENERATED BY DEFAULT AS IDENTITY").format(sql.Identifier(name))
                elif name == "meter_name":
                    definition = sql.SQL("{} TEXT NOT NULL DEFAULT ''").format(sql.Identifier(name))
                elif name in numeric_columns:
                    definition = sql.SQL("{} NUMERIC(20,2)").format(sql.Identifier(name))
                else:
                    definition = sql.SQL("{} {}").format(sql.Identifier(name), sql.SQL(type_sql))
                    if column_default and name not in {"collected_at", "reading_date", "reading_time", "timestamp_source", "meter_name"}:
                        definition += sql.SQL(" DEFAULT ") + sql.SQL(column_default)
                    if is_nullable == "NO":
                        definition += sql.SQL(" NOT NULL")
                definitions.append(definition)

            definitions.extend([
                sql.SQL("PRIMARY KEY (timestamp, id)"),
                sql.SQL("UNIQUE (meter_id, timestamp, timestamp_source)"),
            ])
            cursor.execute(
                sql.SQL("CREATE TABLE {} ({}) PARTITION BY RANGE (timestamp)").format(
                    sql.Identifier(replacement_name), sql.SQL(", ").join(definitions)
                )
            )

            cursor.execute(
                """
                SELECT c.relname, pg_get_expr(c.relpartbound, c.oid)
                FROM pg_inherits i
                JOIN pg_class c ON c.oid = i.inhrelid
                JOIN pg_class p ON p.oid = i.inhparent
                WHERE p.relname = 'readings'
                ORDER BY c.relname
                """
            )
            for old_partition, bound in cursor.fetchall():
                new_partition = replacement_partition_name(old_partition)
                cursor.execute(
                    sql.SQL("CREATE TABLE {} PARTITION OF {} {}").format(
                        sql.Identifier(new_partition), sql.Identifier(replacement_name), sql.SQL(bound)
                    )
                )

            identifiers = sql.SQL(", ").join(sql.Identifier(name) for name in desired)
            source_expressions = []
            for name in desired:
                source_column = sql.Identifier("r", name)
                if name == "meter_name":
                    source_expressions.append(
                        sql.SQL("COALESCE({}, m.meter_name, '')").format(source_column)
                    )
                elif name in numeric_columns:
                    source_expressions.append(
                        sql.SQL("ROUND({}::numeric, 2)").format(source_column)
                    )
                else:
                    source_expressions.append(source_column)
            cursor.execute(
                sql.SQL("INSERT INTO {} ({}) SELECT {} FROM readings").format(
                    sql.Identifier(replacement_name),
                    identifiers,
                    sql.SQL(", ").join(source_expressions),
                )
                + sql.SQL(" AS r LEFT JOIN meters AS m ON m.meter_id = r.meter_id")
            )
            cursor.execute("DROP VIEW IF EXISTS meter_latest_readings")
            cursor.execute(sql.SQL("ALTER TABLE readings RENAME TO {} ").format(sql.Identifier(backup_name)))
            cursor.execute(sql.SQL("ALTER TABLE {} RENAME TO readings").format(sql.Identifier(replacement_name)))
            cursor.execute("CREATE INDEX idx_readings_reordered_meter_timestamp ON readings (meter_id, timestamp DESC)")
            cursor.execute("CREATE INDEX idx_readings_reordered_meter_collected ON readings (meter_id, collected_at DESC)")
            cursor.execute("CREATE INDEX idx_readings_reordered_collected_at ON readings (collected_at)")
            cursor.execute("SELECT setval(pg_get_serial_sequence('readings', 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM readings")

        connection.commit()

    print(f"Rebuilt readings with requested order. Backup retained as public.{backup_name}.")


if __name__ == "__main__":
    main()
